#!/usr/bin/env bash
#
# Undo scripts/install.sh.
#
#   ./scripts/uninstall.sh              # remove what the installer built
#   ./scripts/uninstall.sh --dry-run    # list it, change nothing
#   ./scripts/uninstall.sh --purge      # also delete your data — see below
#   ./scripts/uninstall.sh --yes        # skip the confirmation prompt
#
# By default this removes only things the installer created and can recreate:
# the virtualenv, node_modules, the compiled interface, the downloaded fonts,
# the vendored LaTeX engine, the `opportunity-tracker` command and the PATH
# line it added.
#
# Your database, uploads, logs, .env and resume are LEFT ALONE. Re-running
# install.sh afterwards brings the app back with your data intact. --purge
# deletes those too, and there is no undo for that.
#
# The project directory itself is never removed; delete it yourself when done.

set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"

# Arrays below use the ${arr[@]+"${arr[@]}"} form throughout: bash 3.2, still
# the default /bin/bash on macOS, errors on "${arr[@]}" when the array is empty
# and `set -u` is on.
BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; OFF=$'\033[0m'
step() { printf '\n%s==>%s %s%s\n' "$BOLD" "$OFF" "$1" "$OFF"; }
ok()   { printf '    %s✓%s %s\n' "$GREEN" "$OFF" "$1"; }
warn() { printf '    %s!%s %s\n' "$YELLOW" "$OFF" "$1"; }
keep() { printf '    %s·%s kept  %s\n' "$DIM" "$OFF" "$1"; }

DRY=0
PURGE=0
ASSUME_YES=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY=1; shift ;;
    --purge) PURGE=1; shift ;;
    --yes|-y) ASSUME_YES=1; shift ;;
    -h|--help) sed -n '2,19p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

size_of() { du -sh "$1" 2>/dev/null | cut -f1 || echo "?"; }

# ------------------------------------------------------------------ what we found

BUILT=()
# `vendor` holds the Tectonic binary install.sh downloads when the machine has
# no LaTeX engine. Re-downloadable, so it goes with the rest of the build.
for path in .venv frontend/node_modules frontend/dist vendor; do
  [[ -e "$ROOT/$path" ]] && BUILT+=("$path")
done
shopt -s nullglob
FONTS=("$ROOT"/frontend/public/fonts/*.woff2)
shopt -u nullglob

LAUNCHER="$HOME/.local/bin/opportunity-tracker"
LAUNCHER_IS_OURS=0
# Only remove a launcher this installer wrote. Someone else's command by the
# same name is not ours to delete.
if [[ -f "$LAUNCHER" ]] && grep -q "generated by scripts/install.sh" "$LAUNCHER"; then
  LAUNCHER_IS_OURS=1
fi

MARKER="# Added by Opportunity Tracker (scripts/install.sh)"
RC_FILES=()
for rc in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.profile" "$HOME/.config/fish/config.fish"; do
  [[ -f "$rc" ]] && grep -qF "$MARKER" "$rc" && RC_FILES+=("$rc")
done

USER_DATA=()
for path in data logs .env; do
  [[ -e "$ROOT/$path" ]] && USER_DATA+=("$path")
done

# ------------------------------------------------------------------------ plan

step "This will remove"
for path in ${BUILT[@]+"${BUILT[@]}"}; do printf '    %s  (%s)\n' "$path" "$(size_of "$ROOT/$path")"; done
[[ ${#FONTS[@]} -gt 0 ]] && printf '    frontend/public/fonts/*.woff2  (%s files, re-downloadable)\n' "${#FONTS[@]}"
[[ "$LAUNCHER_IS_OURS" == 1 ]] && printf '    %s\n' "$LAUNCHER"
for rc in ${RC_FILES[@]+"${RC_FILES[@]}"}; do printf '    the PATH line in %s\n' "$rc"; done
if [[ ${#BUILT[@]} -eq 0 && ${#FONTS[@]} -eq 0 && "$LAUNCHER_IS_OURS" == 0 && ${#RC_FILES[@]} -eq 0 ]]; then
  printf '    nothing — it does not look installed\n'
fi

if [[ "$PURGE" == 1 ]]; then
  printf '\n%s%sand PERMANENTLY DELETE your data:%s\n' "$BOLD" "$RED" "$OFF"
  for path in ${USER_DATA[@]+"${USER_DATA[@]}"}; do printf '    %s%s  (%s)%s\n' "$RED" "$path" "$(size_of "$ROOT/$path")" "$OFF"; done
  [[ -e "$ROOT/data/opportunities.db" ]] && printf '    %s^ includes every listing, application and note you have saved%s\n' "$RED" "$OFF"
  [[ -d "$ROOT/data/checkpoints.git" ]] && printf '    %s^ includes the agent'"'"'s undo history%s\n' "$RED" "$OFF"
else
  step "This will keep"
  for path in ${USER_DATA[@]+"${USER_DATA[@]}"}; do keep "$path"; done
  [[ -e "$ROOT/resume.pdf" ]] && keep "resume.pdf"
  [[ -e "$ROOT/resume.txt" ]] && keep "resume.txt"
  keep "the project directory and its git repo"
  # Tectonic's package cache lives outside the project and is shared with any
  # other Tectonic on this machine, so it is never ours to delete.
  for cache in "$HOME/Library/Caches/Tectonic" "$HOME/.cache/Tectonic"; do
    [[ -d "$cache" ]] && keep "$cache  (Tectonic's package cache)"
  done
  printf '\n    %sRe-run ./scripts/install.sh to bring the app back with this intact.%s\n' "$DIM" "$OFF"
  printf '    %sTo delete it as well, re-run with --purge.%s\n' "$DIM" "$OFF"
fi

if [[ "$DRY" == 1 ]]; then
  printf '\n%s--dry-run: nothing was changed.%s\n\n' "$BOLD" "$OFF"
  exit 0
fi

# --------------------------------------------------------------------- confirm

if [[ "$ASSUME_YES" != 1 ]]; then
  printf '\n'
  if [[ "$PURGE" == 1 ]]; then
    # A yes/no prompt is too easy to answer reflexively for something with no undo.
    printf '%sType %sDELETE MY DATA%s to confirm, or anything else to cancel: %s' "$BOLD" "$RED" "$OFF$BOLD" "$OFF"
    read -r reply
    [[ "$reply" == "DELETE MY DATA" ]] || { printf '\nCancelled. Nothing was changed.\n\n'; exit 0; }
  else
    printf '%sProceed? [y/N] %s' "$BOLD" "$OFF"
    read -r reply
    [[ "$reply" == "y" || "$reply" == "Y" ]] || { printf '\nCancelled. Nothing was changed.\n\n'; exit 0; }
  fi
fi

# ----------------------------------------------------------------------- do it

if command -v lsof >/dev/null 2>&1 && lsof -ti :8000 >/dev/null 2>&1; then
  warn "something is still listening on :8000 — stop the app first if that is it"
fi

step "Removing"

for path in ${BUILT[@]+"${BUILT[@]}"}; do
  rm -rf "${ROOT:?}/$path"
  ok "removed $path"
done

if [[ ${#FONTS[@]} -gt 0 ]]; then
  rm -f ${FONTS[@]+"${FONTS[@]}"}
  ok "removed the downloaded fonts"
fi

if [[ "$LAUNCHER_IS_OURS" == 1 ]]; then
  rm -f "$LAUNCHER"
  ok "removed $LAUNCHER"
elif [[ -f "$LAUNCHER" ]]; then
  warn "left $LAUNCHER alone — it was not written by this installer"
fi

for rc in ${RC_FILES[@]+"${RC_FILES[@]}"}; do
  cp "$rc" "$rc.opportunity-tracker.bak"
  # Drop the marker and the single line after it, which is what install.sh
  # appended. Anything else in the file is left exactly as it was.
  awk -v marker="$MARKER" '
    skip { skip = 0; next }
    index($0, marker) { skip = 1; next }
    { print }
  ' "$rc.opportunity-tracker.bak" > "$rc"
  ok "removed the PATH line from $rc (backup: $rc.opportunity-tracker.bak)"
done

if [[ "$PURGE" == 1 ]]; then
  for path in ${USER_DATA[@]+"${USER_DATA[@]}"}; do
    rm -rf "${ROOT:?}/$path"
    ok "deleted $path"
  done
fi

# ------------------------------------------------------------------------ done

step "Done"
if [[ "$PURGE" == 1 ]]; then
  printf '    Everything is gone. Delete %s when you are ready.\n\n' "$ROOT"
else
  printf '    Your data is still in %s/data.\n' "$ROOT"
  printf '    Run ./scripts/install.sh to reinstall, or delete %s to finish.\n\n' "$ROOT"
fi
